# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: adamsapple
email: adamsappletech01@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Technology tips for the Apple centric.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adamsapple.tech" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  adamsappletech


# Build settings
# theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll
show_excerpts: true
# disqus_shortname: aballif
plugins:
  - jekyll-feed

# Set which comment system to use
comments:
  # 'disqus' / 'giscus' / 'utterances' are available
  provider:            giscus

# You must install utterances github app before use.(https://github.com/apps/utterances)
# Make sure all variables are set properly. Check below link for detail.
# https://utteranc.es/
# utterances:
#   repo:                "LazyRen/LazyRen.github.io"
#   issue-term:          "pathname"
#   label:               "Comments"
#   theme:               "dark-blue"

# You must install giscus github app before use.(https://github.com/apps/giscus)
# Make sure all variables are set properly. Check below link for detail.
# https://giscus.vercel.app/
giscus:
  repo:                "adamsappletech/adamsappletech.github.io"
  repo-id:             "R_kgDOK5uboQ"
  category:            "General"
  category-id:         "DIC_kwDOK5uboc4CbzPX"
  mapping:             "pathname"
  reaction-enabled:    "1"
  theme:               "dark_dimmed"
  crossorigin:         "anonymous"


plainwhite:
  portfolio_image:  "assets/adamsapple_thumbnail.png"
 # disqus_shortname: aballif
 # sitemap: true
 # search: true
  dark_mode: true
  name: adamsapple
  tagline: Technology tips for the Apple centric.
  date_format: "%b %-d, %Y"
  social_links:
    github: adamsappletech
  navigation:
    - title: Video
      url: "/video"
    - title: Podcast
      url: "/podcast"
    - title: "Tags"
      url: "/categories"
    - title: "Contact"
      url: "/about"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
